from app.services.login_service import LoginService
from app.services.home_service import HomeService
from app.services.buy_service import BuyService
from app.services.ingred_service import IngredService
from app.services.ingred_form_service import IngredFormService
from app.services.recipe_service import RecipeService
from app.services.recipe_form_service import RecipeFormService
from app.services.menu_plan_service import MenuPlanService
from app.services.app_const_service import AppConstService
from app.services.setting_service import SettingService